### ISSUE TITLE
Option to show tab count for current window only

### ISSUE THREAD

**Issue by HighCommander4** [rixx/tst-tab-count#1]
Thanks very much for writing this!

Would you consider adding an option to only show the tab count for the current window, rather than showing tab counts in each window and the total?

**Comment by rixx** [comment]
Hey! This is was actually my plan, when I encountered piroor/treestyletab#3578. The bug has since been fixed, because piroor is very cool. It's not in a release yet, but once TreeStyleTab v4.0.19 is out, I can put this feature back in.

**Comment by waltcf** [comment]
Looks like v4.0.19 is out! Looking forward to trying your extension, since this change was an unexpected disruption. (That'll teach me to leave auto-updates on!)

**Comment by rixx** [comment]
Ugh, I even subscribed to release notifications, but they seem to only tag their releases 90% of the time. Thanks, I just uploaded the update, now just waiting for Mozilla to approve.

**Comment by HighCommander4** [comment]
Thanks for the update, appreciated!
